time:
  format: "%day%%hour%%minute%%second%"
  empty: " "
  day:
    none: ""
    one: "%time% jour "
    multiple: "%time% jours "
  hour:
    none: ""
    one: "%time% heure "
    multiple: "%time% heures "
  minute:
    none: ""
    one: "%time% minute "
    multiple: "%time% minutes "
  second:
    none: ""
    one: "%time% seconde "
    multiple: "%time% secondes "

noperm: "&cTu n'as pas la permission de faire cette commande"

header: "-----------"
footer: "-----------"
noboost: "Tu n'as pas de boost"

boost:
  xp:
    group: "boost_exp"
    infinite: "Tu possèdes un boost expérience de manière permanente"
    normal: "Tu possèdes un boost éxpérience pendant encore %duration%"
  money:
    group: "boost_money"
    infinite: "Tu possèdes un boost de money de manière permanente"
    normal: "Tu possèdes un boost de money pendant encore %duration%"